In [13]:
import pandas as pd
import numpy
from sklearn import metrics
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
data=pd.read_csv("problem_2_train.csv")

data['mobilepurchasedate']=pd.to_datetime(data['mobilepurchasedate']).dt.day
data['memcreateddate']=pd.to_datetime(data['memcreateddate']).dt.day
data['claimintdate']=pd.to_datetime(data['claimintdate']).dt.day
data['pickupStartdate']=pd.to_datetime(data['pickupStartdate']).dt.day
mob_dict=dict(zip(data['mobmake'].unique(),range(len(data['mobmake'].unique()))))
data['mob_make_code']=data['mobmake'].map(mob_dict)
pin_dict=dict(zip(data['custpincodecategory'].unique(),range(len(data['custpincodecategory'].unique()))))
data['custpincodecategory_code']=data['custpincodecategory'].map(pin_dict)
data['claimtype_code']=data['claimtype'].map({'ADLD':0,'EW':1})

X = data[['srno','mob_make_code','hubid','hubpincode','pickuppartnerid','insuranceCompanyId','claimtype_code','custpincodecategory_code','deliverypartnerid','custpincode','mobilepurchasedate','memcreateddate','claimintdate','pickupStartdate','servicecntrid']]
Y = data['tat_in_days']
# feature extraction
test = SelectKBest(score_func=chi2, k=10)
fit = test.fit(X, Y)
# summarize scores
numpy.set_printoptions(precision=3)
print(fit.scores_)
feature_cols = fit.transform(X)
# summarize selected features
print(feature_cols)

X=data[feature_cols]
#s=data2[feature_cols]
X.dropna(inplace=True)
X.isnull().sum()
y=data['tat_in_days']
y.isnull().sum()
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=1)

#X_train,X_test,y_train,y_test = train_test_split(s,y,test_size=1.0,random_state=1)

from sklearn.linear_model import LinearRegression
#instantiate
linreg=LinearRegression()
#train model to fit the data
linreg.fit(X_train,y_train)
# print("Intercept::",linreg.intercept_)
# print("All coefficients::",linreg.coef_)
list(zip(feature_cols,linreg.coef_))

#predicting on testing data
y_pred=linreg.predict(X_test)


import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
print("root mean square:",np.sqrt(mean_squared_error(y_test, y_pred)))
print(y_pred)
X.describe()
r2_score(y_test, y_pred)

[5.505e+05 4.269e+03 9.176e+02 1.383e+07 7.976e+02 5.975e+02 1.604e+03
 9.867e+02 6.271e+02 1.479e+07 2.526e+02 2.069e+02 3.097e+02 1.685e+02
 1.949e+03]
[[2851218       0       7 ...     233  500001    4403]
 [2838330       1      10 ...     233  226022    4444]
 [2835781       1       2 ...     233  110018    4388]
 ...
 [2999232       3       2 ...     233  110085    4550]
 [2980326      16       2 ...     233  500030    4478]
 [2973922       1       2 ...     233  122001    4388]]


KeyError: "None of [Index([ (2851218, 0, 7, 500004, 233, 0, 0, 233, 500001, 4403),\n       (2838330, 1, 10, 226010, 233, 0, 0, 233, 226022, 4444),\n        (2835781, 1, 2, 110018, 233, 0, 0, 233, 110018, 4388),\n        (2838589, 2, 2, 110018, 233, 0, 1, 233, 124001, 4092),\n       (2855214, 0, 21, 110015, 233, 0, 0, 233, 201301, 4580),\n       (2852784, 0, 21, 110015, 233, 0, 1, 233, 132001, 4580),\n        (2844713, 3, 2, 110018, 233, 0, 0, 233, 110059, 4094),\n        (2829719, 3, 6, 160059, 233, 0, 1, 233, 151001, 4549),\n        (2833619, 0, 3, 560011, 201, 0, 0, 233, 560076, 4467),\n        (2870579, 1, 5, 380009, 233, 0, 1, 233, 390006, 4422),\n       ...\n       (3016763, 0, 26, 560066, 233, 0, 0, 233, 560037, 5001),\n        (2981238, 0, 8, 700064, 233, 0, 0, 233, 700014, 4508),\n        (3072593, 3, 8, 700064, 233, 0, 0, 233, 700007, 4511),\n       (2830968, 0, 17, 800001, 201, 0, 3, 201, 815353, 4410),\n       (2863463, 22, 1, 400059, 233, 0, 1, 233, 452001, 4008),\n        (2949680, 1, 2, 110018, 233, 0, 0, 233, 110032, 4388),\n        (2971901, 5, 1, 400059, 233, 0, 0, 233, 400076, 4011),\n        (2999232, 3, 2, 110018, 233, 0, 0, 233, 110085, 4550),\n       (2980326, 16, 2, 110018, 233, 0, 0, 233, 500030, 4478),\n        (2973922, 1, 2, 110018, 308, 0, 0, 233, 122001, 4388)],\n      dtype='object', length=6250)] are in the [columns]"